# Generated by Django 5.1.4 on 2024-12-12 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["created_at", "updated_at"],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="recipient",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="recipient",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
