# Generated by Django 5.1.4 on 2024-12-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0002_alter_recipient_options_recipient_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="updated_at",
        ),
    ]
