# Generated by Django 5.1.4 on 2024-12-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mail_serv",
            "0003_alter_recipient_options_remove_recipient_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
