# Generated by Django 5.1.4 on 2024-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0004_alter_recipient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
