# Generated by Django 5.1.4 on 2024-12-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0005_alter_recipient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagemanagement",
            name="recipient",
        ),
    ]
