# Generated by Django 5.1.4 on 2024-12-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0007_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mail_serv.messagemanagement",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="mail_serv.recipient", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата запуска"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Создана"),
                    ("Started", "Запущена"),
                    ("Finished", "Завершена"),
                ],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
