# Generated by Django 5.1.4 on 2024-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0008_alter_mailing_created_at_alter_mailing_ended_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
