# Generated by Django 5.1.4 on 2024-12-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0011_emailsendingattempt_owner_mailing_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailsendingattempt",
            name="owner",
        ),
    ]
