# Generated by Django 5.1.4 on 2024-12-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_serv", "0015_emailsendingattempt_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
